from db.models import Categories, Customers, Cities, OrderHistory, Products, Warehouse, ProductsOrderHistory, ProductCities

def create_categories():
    Categories.objects.bulk_create([
        Categories(title='fridge'),
        Categories(title='headphone'),
        Categories(title='laptop'),
        Categories(title='phone'),
        Categories(title='smart watch'),
        Categories(title='stove'),
        Categories(title='tablet'),
        Categories(title='tv'),
        Categories(title='wash machine'),
    ])

def create_customers():
    Customers.objects.bulk_create([
        Customers(first_name='Anthony'),
        Customers(first_name='Barbara'),
        Customers(first_name='James'),
        Customers(first_name='Thomas'),
        Customers(first_name='Karen'),
        Customers(first_name='Elizabeth'),
        Customers(first_name='John'),
        Customers(first_name='Charles'),
        Customers(first_name='Michael'),
        Customers(first_name='William'),
        Customers(first_name='David'),
        Customers(first_name='Jessica'),
        Customers(first_name='Betty'),
        Customers(first_name='Susan'),
        Customers(first_name='Christopher'),
        Customers(first_name='Nancy'),
        Customers(first_name='Jennifer'),
        Customers(first_name='Daniel'),
        Customers(first_name='Sarah'),
        Customers(first_name='Patricia'),
        Customers(first_name='Mark'),
        Customers(first_name='Joseph'),
        Customers(first_name='Lisa'),
        Customers(first_name='Linda'),
        Customers(first_name='Matthew'),
        Customers(first_name='Sandra'),
        Customers(first_name='Robert'),
        Customers(first_name='Mary'),
        Customers(first_name='Richard'),
        Customers(first_name='Margaret'),
    ])
    
def create_cities():
    Cities.objects.bulk_create([
        Cities(title='Almaty'),
        Cities(title='Astana'),
        Cities(title='Shymkent'),
    ])

def create_order_history():
    OrderHistory.objects.bulk_create([
        OrderHistory(order_date='2023-01-04', customer_id=1),
        OrderHistory(order_date='2023-01-05', customer_id=2),
        OrderHistory(order_date='2023-01-05', customer_id=3),
        OrderHistory(order_date='2023-01-06', customer_id=4),
        OrderHistory(order_date='2023-01-06', customer_id=5),
        OrderHistory(order_date='2023-01-06', customer_id=6),
        OrderHistory(order_date='2023-01-08', customer_id=7),
        OrderHistory(order_date='2023-01-09', customer_id=8),
        OrderHistory(order_date='2023-01-09', customer_id=9),
        OrderHistory(order_date='2023-01-10', customer_id=10),
        OrderHistory(order_date='2023-01-11', customer_id=11),
        OrderHistory(order_date='2023-01-11', customer_id=12),
        OrderHistory(order_date='2023-01-13', customer_id=13),
        OrderHistory(order_date='2023-01-14', customer_id=14),
        OrderHistory(order_date='2023-01-15', customer_id=15),
        OrderHistory(order_date='2023-01-16', customer_id=16),
        OrderHistory(order_date='2023-01-17', customer_id=17),
        OrderHistory(order_date='2023-01-17', customer_id=18),
        OrderHistory(order_date='2023-01-18', customer_id=19),
        OrderHistory(order_date='2023-01-19', customer_id=20),
        OrderHistory(order_date='2023-01-19', customer_id=21),
        OrderHistory(order_date='2023-01-19', customer_id=22),
        OrderHistory(order_date='2023-01-21', customer_id=23),
        OrderHistory(order_date='2023-01-22', customer_id=24),
        OrderHistory(order_date='2023-01-23', customer_id=25),
        OrderHistory(order_date='2023-01-24', customer_id=26),
        OrderHistory(order_date='2023-01-24', customer_id=27),
        OrderHistory(order_date='2023-01-26', customer_id=28),
        OrderHistory(order_date='2023-01-27', customer_id=29),
        OrderHistory(order_date='2023-01-29', customer_id=30),
        OrderHistory(order_date='2023-01-29', customer_id=30),
    ])

def create_products():
    Products.objects.bulk_create([
        Products(title='Atlant MXM-2835-90', company='Atlant', product_count=7, price=164990, category_id=1),
        Products(title='Beko RCSK-250M00W', company='Beko', product_count=5, price=159990, category_id=1),
        Products(title='Bosch KGN39XW326', company='Bosch', product_count=10, price=374990, category_id=1),
        Products(title='Dauscher DRF-17DTW', company='Dauscher', product_count=7, price=119990, category_id=1),
        Products(title='Gorenje NRK619FAW4', company='Gorenje', product_count=10, price=229990, category_id=1),
        Products(title='LG GC-B509SESM', company='LG', product_count=3, price=359990, category_id=1),
        Products(title='Liebherr CNsdd 5753-20 001', company='Liebherr', product_count=12, price=791990, category_id=1),
        Products(title='Midea MDRB521MGE34T', company='Midea', product_count=10, price=329990, category_id=1),
        Products(title='Samsung RB-37A5200SA', company='Samsung', product_count=13, price=289990, category_id=1),
        Products(title='Toshiba GR-RF610WE-PMS', company='Toshiba', product_count=9, price=679990, category_id=1),
        Products(title='Apple AirPods', company='Apple', product_count=9, price=74990, category_id=2),
        Products(title='Bang & Olufsen BeoPlay EQ', company='Bang & Olufsen', product_count=1, price=249990, category_id=2),
        Products(title='Beats Studio Buds', company='Beats Electronics', product_count=2, price=79990, category_id=2),
        Products(title='JBL Bluetooth Tune 760 NC', company='JBL', product_count=2, price=69990, category_id=2),
        Products(title='Samsung Bluetooth Galaxy Buds2', company='Samsung', product_count=5, price=69990, category_id=2),
        Products(title='Acer Aspire 3 i3', company='Acer', product_count=8, price=179990, category_id=3),
        Products(title='Apple MacBook Air M1', company='Apple', product_count=5, price=529900, category_id=3),
        Products(title='Asus TUF Gaming F15 i5', company='Asus', product_count=5, price=349890, category_id=3),
        Products(title='Dell Vostro 3515 Ryzen 3', company='Dell', product_count=3, price=299990, category_id=3),
        Products(title='Gigabyte U4', company='Gigabyte', product_count=2, price=479990, category_id=3),
        Products(title='HP 15s-eq1162ur Ryzen 3', company='HP', product_count=6, price=189890, category_id=3),
        Products(title='HUAWEI MateBook D15 Ryzen 5', company='Huawei', product_count=2, price=299990, category_id=3),
        Products(title='Lenovo Legion 5 Pro Ryzen 7', company='Lenovo', product_count=7, price=599990, category_id=3),
        Products(title='LG Gram i7', company='LG', product_count=2, price=806290, category_id=3),
        Products(title='Xiaomi RedmiBook i3', company='Xiaomi', product_count=3, price=219990, category_id=3),
        Products(title='Apple iPhone 14 Pro', company='Apple', product_count=10, price=579990, category_id=4),
        Products(title='Huawei P60 Pro', company='Huawei', product_count=5, price=649990, category_id=4),
        Products(title='Motorola G52', company='Motorola', product_count=2, price=139990, category_id=4),
        Products(title='Samsung Galaxy A24', company='Samsung', product_count=9, price=129990, category_id=4),
        Products(title='Xiaomi 13 Lite', company='Xiaomi', product_count=4, price=219990, category_id=4),
        Products(title='Apple Watch SE 2022', company='Apple', product_count=6, price=134990, category_id=5),
        Products(title='Garmin Fenix 7X', company='Garmin', product_count=3, price=630990, category_id=5),
        Products(title='Samsung Galaxy Watch5 Pro', company='Samsung', product_count=8, price=199990, category_id=5),
        Products(title='Suunto 9 Baro Titanium', company='Suunto Oy', product_count=3, price=319890, category_id=5),
        Products(title='Amazfit GTR 3', company='Zepp Health', product_count=2, price=79990, category_id=5),
        Products(title='Artel OTTIMA G 50x57', company='Artel', product_count=10, price=74990, category_id=6),
        Products(title='Beko FSM-67300GWS', company='Beko', product_count=5, price=244990, category_id=6),
        Products(title='Bosch HXS-59AI20Q', company='Bosch', product_count=5, price=359990, category_id=6),
        Products(title='Dauscher E9403LX', company='Dauscher', product_count=7, price=214990, category_id=6),
        Products(title='Gefest 1200-K19', company='Gefest', product_count=7, price=129990, category_id=6),
        Products(title='Gorenje GEC6C60WA', company='Gorenje', product_count=3, price=309990, category_id=6),
        Products(title='Hansa FCCW-680009', company='Hansa', product_count=7, price=189990, category_id=6),
        Products(title='SMEG SX91GM', company='SMEG', product_count=6, price=568990, category_id=6),
        Products(title='Apple iPad 10.2 2021', company='Apple', product_count=8, price=169990, category_id=7),
        Products(title='HUAWEI MatePad T 10', company='Huawei', product_count=5, price=104990, category_id=7),
        Products(title='Lenovo Tab M10', company='Lenovo', product_count=3, price=69790, category_id=7),
        Products(title='Samsung Galaxy Tab A8', company='Samsung', product_count=9, price=119990, category_id=7),
        Products(title='Xiaomi PAD 5', company='Xiaomi', product_count=3, price=197990, category_id=7),
        Products(title='Bang & Olufsen 40" BeoVision Horizon', company='Bang & Olufsen', product_count=2, price=1574990, category_id=8),
        Products(title='Hisense 32" 32A4BG HD Smart Black', company='Hisense', product_count=13, price=74990, category_id=8),
        Products(title='LG 55" 55UQ76003LD LED UHD Smart Gray', company='LG', product_count=2, price=269990, category_id=8),
        Products(title='Philips 58 58PUS8507/60 LED UHD Android Silver', company='Philips', product_count=10, price=449990, category_id=8),
        Products(title='Samsung 65" UE65BU8000UXCE LED UHD Smart Black', company='Samsung', product_count=5, price=379990, category_id=8),
        Products(title='Sony 65" KD65X81JR LED UHD Smart Black', company='Sony', product_count=9, price=699990, category_id=8),
        Products(title='Toshiba 43" 43C350LE UHD Black', company='Toshiba', product_count=4, price=129990, category_id=8),
        Products(title='Beko WRS-5511BWW', company='Beko', product_count=5, price=114990, category_id=9),
        Products(title='Bosch WAV-28M80ME', company='Bosch', product_count=3, price=629990, category_id=9),
        Products(title='Dauscher WMD-14000DD-BMW', company='Dauscher', product_count=9, price=449990, category_id=9),
        Products(title='Gorenje W1NHEI62SAS', company='Gorenje', product_count=3, price=149990, category_id=9),
        Products(title='LG F2J6HSDS', company='LG', product_count=8, price=264990, category_id=9),
        Products(title='Midea MFH180-G802DS', company='Midea', product_count=6, price=499990, category_id=9),
        Products(title='Samsung WW60J32G0PW/LD', company='Samsung', product_count=5, price=189990, category_id=9),
        Products(title='Toshiba TW-BL90A4UZ', company='Toshiba', product_count=2, price=249990, category_id=9),
    ])

def create_warehouse():
    Warehouse.objects.bulk_create([
        Warehouse(city_id=1, product_count=7, product_id=1),
        Warehouse(city_id=1, product_count=6, product_id=3),
        Warehouse(city_id=1, product_count=6, product_id=5),
        Warehouse(city_id=1, product_count=8, product_id=7),
        Warehouse(city_id=1, product_count=8, product_id=8),
        Warehouse(city_id=1, product_count=7, product_id=9),
        Warehouse(city_id=1, product_count=3, product_id=11),
        Warehouse(city_id=1, product_count=6, product_id=16),
        Warehouse(city_id=1, product_count=4, product_id=17),
        Warehouse(city_id=1, product_count=6, product_id=26),
        Warehouse(city_id=1, product_count=5, product_id=29),
        Warehouse(city_id=1, product_count=6, product_id=33),
        Warehouse(city_id=1, product_count=5, product_id=36),
        Warehouse(city_id=1, product_count=4, product_id=44),
        Warehouse(city_id=1, product_count=6, product_id=50),
        Warehouse(city_id=1, product_count=7, product_id=52),
        Warehouse(city_id=1, product_count=6, product_id=60),
        Warehouse(city_id=1, product_count=5, product_id=2),
        Warehouse(city_id=1, product_count=7, product_id=4),
        Warehouse(city_id=1, product_count=3, product_id=6),
        Warehouse(city_id=1, product_count=3, product_id=10),
        Warehouse(city_id=1, product_count=1, product_id=12),
        Warehouse(city_id=1, product_count=2, product_id=13),
        Warehouse(city_id=1, product_count=2, product_id=14),
        Warehouse(city_id=1, product_count=5, product_id=15),
        Warehouse(city_id=1, product_count=5, product_id=18),
        Warehouse(city_id=1, product_count=3, product_id=19),
        Warehouse(city_id=1, product_count=2, product_id=20),
        Warehouse(city_id=1, product_count=6, product_id=21),
        Warehouse(city_id=1, product_count=2, product_id=22),
        Warehouse(city_id=1, product_count=7, product_id=23),
        Warehouse(city_id=1, product_count=2, product_id=24),
        Warehouse(city_id=1, product_count=3, product_id=25),
        Warehouse(city_id=1, product_count=5, product_id=27),
        Warehouse(city_id=1, product_count=2, product_id=28),
        Warehouse(city_id=1, product_count=4, product_id=30),
        Warehouse(city_id=1, product_count=6, product_id=31),
        Warehouse(city_id=1, product_count=3, product_id=32),
        Warehouse(city_id=1, product_count=3, product_id=34),
        Warehouse(city_id=1, product_count=2, product_id=35),
        Warehouse(city_id=1, product_count=5, product_id=37),
        Warehouse(city_id=1, product_count=5, product_id=38),
        Warehouse(city_id=1, product_count=7, product_id=39),
        Warehouse(city_id=1, product_count=7, product_id=40),
        Warehouse(city_id=1, product_count=3, product_id=41),
        Warehouse(city_id=1, product_count=7, product_id=42),
        Warehouse(city_id=1, product_count=6, product_id=43),
        Warehouse(city_id=1, product_count=5, product_id=45),
        Warehouse(city_id=1, product_count=3, product_id=46),
        Warehouse(city_id=1, product_count=5, product_id=47),
        Warehouse(city_id=1, product_count=3, product_id=48),
        Warehouse(city_id=1, product_count=2, product_id=49),
        Warehouse(city_id=1, product_count=2, product_id=51),
        Warehouse(city_id=1, product_count=5, product_id=53),
        Warehouse(city_id=1, product_count=9, product_id=54),
        Warehouse(city_id=1, product_count=4, product_id=55),
        Warehouse(city_id=1, product_count=5, product_id=56),
        Warehouse(city_id=1, product_count=3, product_id=57),
        Warehouse(city_id=1, product_count=9, product_id=58),
        Warehouse(city_id=1, product_count=3, product_id=59),
        Warehouse(city_id=1, product_count=6, product_id=61),
        Warehouse(city_id=1, product_count=5, product_id=62),
        Warehouse(city_id=1, product_count=2, product_id=63),
        Warehouse(city_id=2, product_count=2, product_id=47),
        Warehouse(city_id=2, product_count=3, product_id=10),
        Warehouse(city_id=2, product_count=2, product_id=3),
        Warehouse(city_id=2, product_count=2, product_id=5),
        Warehouse(city_id=2, product_count=2, product_id=7),
        Warehouse(city_id=2, product_count=1, product_id=8),
        Warehouse(city_id=2, product_count=3, product_id=9),
        Warehouse(city_id=2, product_count=3, product_id=11),
        Warehouse(city_id=2, product_count=1, product_id=16),
        Warehouse(city_id=2, product_count=2, product_id=10),
        Warehouse(city_id=2, product_count=2, product_id=29),
        Warehouse(city_id=2, product_count=1, product_id=33),
        Warehouse(city_id=2, product_count=3, product_id=36),
        Warehouse(city_id=2, product_count=2, product_id=44),
        Warehouse(city_id=2, product_count=4, product_id=50),
        Warehouse(city_id=2, product_count=1, product_id=52),
        Warehouse(city_id=2, product_count=2, product_id=60),
        Warehouse(city_id=3, product_count=2, product_id=47),
        Warehouse(city_id=3, product_count=3, product_id=10),
        Warehouse(city_id=3, product_count=2, product_id=3),
        Warehouse(city_id=3, product_count=2, product_id=5),
        Warehouse(city_id=3, product_count=2, product_id=7),
        Warehouse(city_id=3, product_count=1, product_id=8),
        Warehouse(city_id=3, product_count=3, product_id=9),
        Warehouse(city_id=3, product_count=3, product_id=11),
        Warehouse(city_id=3, product_count=1, product_id=16),
        Warehouse(city_id=3, product_count=1, product_id=17),
        Warehouse(city_id=3, product_count=2, product_id=26),
        Warehouse(city_id=3, product_count=2, product_id=29),
        Warehouse(city_id=3, product_count=1, product_id=33),
        Warehouse(city_id=3, product_count=2, product_id=36),
        Warehouse(city_id=3, product_count=2, product_id=44),
        Warehouse(city_id=3, product_count=3, product_id=50),
        Warehouse(city_id=3, product_count=2, product_id=52),
    ])

def create_product_cities():
    ProductCities.objects.bulk_create([
        ProductCities(products_id=1, cities_id=1),
        ProductCities(products_id=3, cities_id=1), 
        ProductCities(products_id=5, cities_id=1), 
        ProductCities(products_id=7, cities_id=1), 
        ProductCities(products_id=8, cities_id=1), 
        ProductCities(products_id=9, cities_id=1),
        ProductCities(products_id=11, cities_id=1),
        ProductCities(products_id=16, cities_id=1),
        ProductCities(products_id=17, cities_id=1),
        ProductCities(products_id=26, cities_id=1),
        ProductCities(products_id=29, cities_id=1),
        ProductCities(products_id=33, cities_id=1),
        ProductCities(products_id=36, cities_id=1),
        ProductCities(products_id=44, cities_id=1),
        ProductCities(products_id=50, cities_id=1),
        ProductCities(products_id=52, cities_id=1),
        ProductCities(products_id=60, cities_id=1),
        ProductCities(products_id=2, cities_id=1),
        ProductCities(products_id=4, cities_id=1),
        ProductCities(products_id=6, cities_id=1),
        ProductCities(products_id=10, cities_id=1),
        ProductCities(products_id=12, cities_id=1),
        ProductCities(products_id=13, cities_id=1),
        ProductCities(products_id=14, cities_id=1),
        ProductCities(products_id=15, cities_id=1),
        ProductCities(products_id=18, cities_id=1),
        ProductCities(products_id=19, cities_id=1),
        ProductCities(products_id=20, cities_id=1),
        ProductCities(products_id=21, cities_id=1),
        ProductCities(products_id=22, cities_id=1),
        ProductCities(products_id=23, cities_id=1),
        ProductCities(products_id=24, cities_id=1),
        ProductCities(products_id=25, cities_id=1),
        ProductCities(products_id=27, cities_id=1),
        ProductCities(products_id=28, cities_id=1),
        ProductCities(products_id=30, cities_id=1),
        ProductCities(products_id=31, cities_id=1),
        ProductCities(products_id=32, cities_id=1),
        ProductCities(products_id=34, cities_id=1),
        ProductCities(products_id=35, cities_id=1),
        ProductCities(products_id=37, cities_id=1),
        ProductCities(products_id=38, cities_id=1),
        ProductCities(products_id=39, cities_id=1),
        ProductCities(products_id=40, cities_id=1),
        ProductCities(products_id=41, cities_id=1),
        ProductCities(products_id=42, cities_id=1),
        ProductCities(products_id=43, cities_id=1),
        ProductCities(products_id=45, cities_id=1),
        ProductCities(products_id=46, cities_id=1),
        ProductCities(products_id=47, cities_id=1),
        ProductCities(products_id=48, cities_id=1),
        ProductCities(products_id=49, cities_id=1),
        ProductCities(products_id=51, cities_id=1),
        ProductCities(products_id=53, cities_id=1),
        ProductCities(products_id=54, cities_id=1),
        ProductCities(products_id=55, cities_id=1),
        ProductCities(products_id=56, cities_id=1),
        ProductCities(products_id=57, cities_id=1),
        ProductCities(products_id=58, cities_id=1),
        ProductCities(products_id=59, cities_id=1),
        ProductCities(products_id=61, cities_id=1),
        ProductCities(products_id=62, cities_id=1),
        ProductCities(products_id=63, cities_id=1),
        ProductCities(products_id=47, cities_id=2),
        ProductCities(products_id=10, cities_id=2),
        ProductCities(products_id=3, cities_id=2),
        ProductCities(products_id=5, cities_id=2),
        ProductCities(products_id=7, cities_id=2),
        ProductCities(products_id=8, cities_id=2),
        ProductCities(products_id=9, cities_id=2),
        ProductCities(products_id=11, cities_id=2),
        ProductCities(products_id=16, cities_id=2),
        ProductCities(products_id=26, cities_id=2),
        ProductCities(products_id=29, cities_id=2),
        ProductCities(products_id=33, cities_id=2),
        ProductCities(products_id=36, cities_id=2),
        ProductCities(products_id=44, cities_id=2),
        ProductCities(products_id=50, cities_id=2),
        ProductCities(products_id=52, cities_id=2),
        ProductCities(products_id=60, cities_id=2),
        ProductCities(products_id=47, cities_id=3),
        ProductCities(products_id=10, cities_id=3),
        ProductCities(products_id=3, cities_id=3),
        ProductCities(products_id=5, cities_id=3),
        ProductCities(products_id=7, cities_id=3),
        ProductCities(products_id=8, cities_id=3),
        ProductCities(products_id=9, cities_id=3),
        ProductCities(products_id=11, cities_id=3),
        ProductCities(products_id=16, cities_id=3),
        ProductCities(products_id=17, cities_id=3),
        ProductCities(products_id=26, cities_id=3),
        ProductCities(products_id=29, cities_id=3),
        ProductCities(products_id=33, cities_id=3),
        ProductCities(products_id=36, cities_id=3),
        ProductCities(products_id=44, cities_id=3),
        ProductCities(products_id=50, cities_id=3),
        ProductCities(products_id=52, cities_id=3),
    ])

def create_products_orderhistory():
    ProductsOrderHistory.objects.bulk_create([
        ProductsOrderHistory(products_id=7, orderhistory_id=1),
        ProductsOrderHistory(products_id=60, orderhistory_id=2),
        ProductsOrderHistory(products_id=26, orderhistory_id=3),
        ProductsOrderHistory(products_id=11, orderhistory_id=4),
        ProductsOrderHistory(products_id=32, orderhistory_id=5),
        ProductsOrderHistory(products_id=52, orderhistory_id=6),
        ProductsOrderHistory(products_id=12, orderhistory_id=7),
        ProductsOrderHistory(products_id=26, orderhistory_id=8),
        ProductsOrderHistory(products_id=47, orderhistory_id=9),
        ProductsOrderHistory(products_id=29, orderhistory_id=10),
        ProductsOrderHistory(products_id=31, orderhistory_id=11),
        ProductsOrderHistory(products_id=60, orderhistory_id=12),
        ProductsOrderHistory(products_id=34, orderhistory_id=13),
        ProductsOrderHistory(products_id=15, orderhistory_id=14),
        ProductsOrderHistory(products_id=11, orderhistory_id=15),
        ProductsOrderHistory(products_id=17, orderhistory_id=16),
        ProductsOrderHistory(products_id=21, orderhistory_id=17),
        ProductsOrderHistory(products_id=47, orderhistory_id=18),
        ProductsOrderHistory(products_id=9, orderhistory_id=19),
        ProductsOrderHistory(products_id=13, orderhistory_id=20),
        ProductsOrderHistory(products_id=29, orderhistory_id=21),
        ProductsOrderHistory(products_id=56, orderhistory_id=22),
        ProductsOrderHistory(products_id=19, orderhistory_id=23),
        ProductsOrderHistory(products_id=53, orderhistory_id=24),
        ProductsOrderHistory(products_id=26, orderhistory_id=25),
        ProductsOrderHistory(products_id=17, orderhistory_id=26),
        ProductsOrderHistory(products_id=38, orderhistory_id=27),
        ProductsOrderHistory(products_id=26, orderhistory_id=28),
        ProductsOrderHistory(products_id=51, orderhistory_id=29),
        ProductsOrderHistory(products_id=40, orderhistory_id=30),
        ProductsOrderHistory(products_id=1, orderhistory_id=31),
    ])
